package communication;

import java.io.Serializable;

public enum Operacija implements Serializable {
    PRIJAVA, ODJAVA,

    DODAJ_KUPCA, PRIKAZI_KUPCE, IZMENI_KUPCA, OBRISI_KUPCA, USLOV_KUPAC,
    DODAJ_KATEGORIJU, PRIKAZI_KATEGORIJE, IZMENI_KATEGORIJU, OBRISI_KATEGORIJU,
    DODAJ_KNJIGU, PRIKAZI_KNJIGE, IZMENI_KNJIGU, OBRISI_KNJIGU, USLOV_KNJIGA,
    DODAJ_RADNIKA, PRIKAZI_RADNIKE, IZMENI_RADNIKA, OBRISI_RADNIKA, USLOV_RADNIK,
    DODAJ_SMENU, PRIKAZI_SMENE, IZMENI_SMENU, OBRISI_SMENU,
    DODAJ_RACUN, PRIKAZI_RACUNE, IZMENI_RACUN, USLOV_RACUN,
    DODAJ_RADNIKSMENU, PRIKAZI_RADNIKSMENE, IZMENI_RADNIKSMENU, OBRISI_RADNIKSMENU;
}
